import "bootstrap/dist/css/bootstrap.css";
import "../css/all.min.css";
import "../css/navbar.css";
import "../css/footer.css";
import "../css/register.css";
import "jquery";
import "popper.js";
import "bootstrap";
import "../js/navbar";
